// 内部产品接口：授权上下文→归属校验/一致冻结→只用不可变数据装配单HTML。
import path from 'node:path'
import {readFile,realpath,lstat,readdir,open,mkdtemp,rm} from 'node:fs/promises'
import {constants} from 'node:fs'
import {fileURLToPath,pathToFileURL} from 'node:url'
import {createHash} from 'node:crypto'
import {tmpdir} from 'node:os'
import {setImmediate as tick} from 'node:timers/promises'
import {assertRepoTopLevel,MAX_FILE_BYTES} from './git.ts'
import {readRoomLayout} from './room.ts'
import {parseChartContract,readChartSet} from './chart-contract.ts'
import {chartRenderer} from './chart-renderer.ts'
import {TYPED_FILE_KEY} from './chart-files.ts'
import {renderArchify} from './archify-render.ts'
import {exportReferences} from './room-export-sources.ts'
import type {RoomLayoutRead} from './types.ts'

export const ROOM_EXPORT_FORMAT='specdev-room-export/1' as const
export const ROOM_EXPORT_LIMITS={documents:64,charts:16,inputBytes:32*1024*1024,intermediateBytes:48*1024*1024,outputBytes:64*1024*1024} as const
export interface ExportLimits {documents:number;charts:number;inputBytes:number;intermediateBytes:number;outputBytes:number}
export interface ExportContext {repoRoot:string;businessId:string;temporaryRoot?:string}
export interface ExportOptions {materials?:readonly string[];theme:'light'|'dark';brightness:number;signal?:AbortSignal;limits?:Partial<ExportLimits>}
export interface ExportIssue {code:string;message:string;materialId?:string}
export interface ExportMaterial {id:string;kind:'document'|'workflow'|'lifecycle';title:string;sha256:string;sourceStatus?:'none'|'missing-remote'|'contract-verified';remoteReachability?:'not-checked'}
export interface ExportSummary {format:typeof ROOM_EXPORT_FORMAT;businessId:string;name:string;theme:'light'|'dark';brightness:number;materials:readonly ExportMaterial[];sha256:string;resourceSha256:string;preparedAt:string;limits:ExportLimits}
export interface PreparedRoomExport {format:typeof ROOM_EXPORT_FORMAT;summary:ExportSummary}
export type PrepareResult={ok:true;prepared:PreparedRoomExport;summary:ExportSummary}|{ok:false;issues:ExportIssue[]}
export type GenerateResult={ok:true;html:Buffer;bytes:number;filename:string;sha256:string;summary:ExportSummary}|{ok:false;issues:ExportIssue[]}
interface Hooks {renderer?:typeof renderArchify;afterCapture?:()=>Promise<void>}
interface Payload {room:RoomLayoutRead;resources:Record<string,any>;documents:{path:string;text:string}[];charts:Record<string,{data:any}>;missingByInstance:string[];theme:'light'|'dark';brightness:number;limits:ExportLimits}
const preparedData=new WeakMap<PreparedRoomExport,{data:Payload;assets:Record<string,string>}>()
let operationInFlight=false,rendererStopped=false
const hash=(value:string|Buffer)=>createHash('sha256').update(value).digest('hex')
const inside=(root:string,file:string)=>{const relative=path.relative(root,file);return relative!== '..'&&!relative.startsWith('..'+path.sep)&&!path.isAbsolute(relative)}
const idPattern=/^[a-z0-9][a-z0-9._-]*$/i

// 选择目录只读取登记描述和文件身份，不读取文档正文、图源、说明或源码证据。
export async function readRoomExportCatalog(context:ExportContext){
  if(!idPattern.test(context.businessId))throw new Error('业务ID不合法')
  const root=await realpath(context.repoRoot);await assertRepoTopLevel(root,{originalObjects:true})
  let metadataBytes=0
  const descriptor=async(relative:string)=>{const file=await checkedPath(root,relative);if(!file)throw new Error('登记描述缺失');const before=await lstat(file);if(!before.isFile()||before.nlink!==1||before.size>MAX_FILE_BYTES)throw new Error('登记描述不可读');if(metadataBytes+before.size>4*1024*1024)throw new ExportError('catalog-limit','资料登记描述累计超过4MiB');const handle=await open(file,constants.O_RDONLY|(constants.O_NOFOLLOW||0));try{const info=await handle.stat();if(info.dev!==before.dev||info.ino!==before.ino||!info.isFile()||info.nlink!==1)throw new Error('登记身份变化');const bytes=await handle.readFile();metadataBytes+=bytes.length;if(bytes.length>MAX_FILE_BYTES||metadataBytes>4*1024*1024)throw new ExportError('catalog-limit','资料登记描述超过读取上限');return{data:JSON.parse(bytes.toString('utf8')),digest:hash(bytes),identity:[info.dev,info.ino,info.size,info.mtimeMs,info.ctimeMs].join(':')}}finally{await handle.close()}}
  const base='docs/specdev/'+context.businessId,{data:business}=await descriptor(base+'/business.json')
  if(business.schema!=='specdev/business/1'||business.id!==context.businessId||typeof business.name!=='string'||!Array.isArray(business.docs)||business.docs.some((x:any)=>typeof x!=='string'))throw new Error('业务登记不合法')
  if(business.docs.length>512)throw new Error('资料目录超过可展示上限')
  const materials:{id:string;title:string;kind:string;identity:string}[]=[]
  for(const doc of new Set<string>(business.docs)){validPath(doc,false);let identity='missing';try{const file=await checkedPath(root,doc);if(file){const info=await lstat(file);identity=[info.dev,info.ino,info.size,info.mtimeMs,info.ctimeMs].join(':')}}catch{identity='unreadable'}materials.push({id:'doc:'+doc,title:doc,kind:'document',identity:hash(JSON.stringify([context.businessId,doc,identity]))})}
  const directory=await checkedPath(root,base);if(!directory)throw new Error('业务目录缺失')
  for(const name of (await readdir(directory,{withFileTypes:true})).filter(x=>x.isDirectory()&&idPattern.test(x.name)).map(x=>x.name).sort()){
    if(!await checkedPath(root,base+'/'+name+'/chart.json'))continue
    if(materials.length>=512)throw new Error('资料目录超过可展示上限')
    try{const item=await descriptor(base+'/'+name+'/chart.json');materials.push({id:'chart:'+name,title:typeof item.data.name==='string'?item.data.name:name,kind:item.data.diagramType==='lifecycle'?'lifecycle':'workflow',identity:hash(JSON.stringify([context.businessId,name,item.digest,item.identity]))})}
    catch(error){if((error as ExportError).code==='catalog-limit')throw error;materials.push({id:'chart:'+name,title:name,kind:'chart',identity:hash(JSON.stringify([context.businessId,name,'invalid']))})}
  }
  if(materials.length>512)throw new Error('资料目录超过可展示上限')
  return{businessId:context.businessId,name:business.name,materials,limits:ROOM_EXPORT_LIMITS}
}
class ExportError extends Error {readonly code:string;readonly materialId?:string;constructor(code:string,message:string,materialId?:string){super(message);this.code=code;this.materialId=materialId}}
const cancel=(signal?:AbortSignal)=>{if(signal?.aborted)throw new ExportError('export-cancelled','导出已取消，不生成文件')}
const freeze=<T>(value:T):T=>{if(value&&typeof value==='object'){Object.freeze(value);for(const child of Object.values(value))freeze(child)}return value}
function limitsFor(value?:Partial<ExportLimits>):ExportLimits {const limits={...ROOM_EXPORT_LIMITS,...value};for(const key of Object.keys(limits) as (keyof ExportLimits)[])if(!Object.hasOwn(ROOM_EXPORT_LIMITS,key)||!Number.isSafeInteger(limits[key])||limits[key]<1||limits[key]>ROOM_EXPORT_LIMITS[key])throw new ExportError('export-limit','导出限额必须是正整数且不能超过产品上限');return limits}
const packageRoot=()=>fileURLToPath(new URL(import.meta.url.endsWith('/src/core/room-export.ts')?'../../':'../',import.meta.url))
const validPath=(relative:string,credentials=true)=>{const parts=relative.split('/');if(!relative||path.isAbsolute(relative)||/[:\\\u0000-\u001f\u007f]/.test(relative)||parts.some(x=>!x||x==='.'||x==='..'||x.toLowerCase()==='.git'))throw new ExportError('export-path','资料路径必须是安全的仓内相对路径');if(credentials&&parts.some(x=>/^(?:\.env(?:\..*)?|\.npmrc|\.netrc|\.git-credentials|\.ssh|\.aws|\.gnupg|id_rsa|id_ed25519|credentials(?:\.json|\.ya?ml)?|secrets?\.(?:json|ya?ml)|.*\.(?:pem|key|p12|pfx))$/i.test(x)))throw new ExportError('export-path','凭据或私钥文件不能作为分享资料')}
async function checkedPath(root:string,relative:string){validPath(relative);let current=root;for(const part of relative.split('/')){current=path.join(current,part);try{const info=await lstat(current);if(info.isSymbolicLink())throw new ExportError('export-path','资料路径包含符号链接或junction');const actual=await realpath(current);if(!inside(root,actual))throw new ExportError('export-path','资料路径越出授权目录')}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return null;throw error}}return current}
async function assets(){const root=await realpath(packageRoot()),base=await checkedPath(root,'dist/offline/manifest.json');if(!base)throw new ExportError('export-assets','安装包缺离线资源，请检查完整包');const manifest=JSON.parse(await readFile(base,'utf8')),result:Record<string,string>={};if(manifest.format!=='specdev-room-offline-assets/1')throw new ExportError('export-assets','离线资源版本不符');for(const name of ['room.html','chart.html','room.js','chart.js','resources.json','bridge.js','licenses.json']){const file=await checkedPath(root,'dist/offline/'+name);if(!file)throw new ExportError('export-assets','安装包离线资源缺失：'+name);const bytes=await readFile(file);if(hash(bytes)!==manifest.files[name])throw new ExportError('export-assets','安装包离线资源摘要不符：'+name);result[name]=bytes.toString('utf8')}return {root,result,manifestHash:hash(JSON.stringify(manifest.files))}}
function sourcePath(source:any){if(!source||typeof source.path!=='string'||Object.keys(source).some(x=>!['path','line','end_line','label'].includes(x)))throw new ExportError('export-source','源码来源含不支持字段');validPath(source.path);if(!Number.isSafeInteger(source.line)||source.line<1||!Number.isSafeInteger(source.end_line??source.line)||(source.end_line??source.line)<source.line)throw new ExportError('export-source','导出源码链接需明确合法行范围');if(source.label!==undefined&&typeof source.label!=='string')throw new ExportError('export-source','源码来源标签非法')}
export async function prepareRoomExport(context:ExportContext,options:ExportOptions,hooks:Hooks={}):Promise<PrepareResult>{
  if(rendererStopped)return{ok:false,issues:[{code:'export-renderer-stopped',message:'渲染停止状态待核实，本进程不自动重试'}]}
  if(operationInFlight)return{ok:false,issues:[{code:'export-busy',message:'已有导出任务在处理；本接口不无限排队'}]}
  operationInFlight=true
  const issues:ExportIssue[]=[];let temporary:string|undefined,cleanupSafe=true
  try{
    cancel(options.signal);const limits=limitsFor(options.limits);if(!idPattern.test(context.businessId)||!['light','dark'].includes(options.theme)||!Number.isFinite(options.brightness)||options.brightness<0||options.brightness>100)throw new ExportError('export-input','业务、主题或亮度参数非法')
    const root=await realpath(context.repoRoot);await assertRepoTopLevel(root,{originalObjects:true});const loaded=await assets(),captured=new Map<string,{digest:string;identity:string}>();let inputBytes=0,intermediateBytes=0
    const read=async(relative:string):Promise<string|null>=>{cancel(options.signal);const file=await checkedPath(root,relative);if(!file){captured.set(relative,{digest:'missing',identity:'missing'});return null}const before=await lstat(file);if(!before.isFile()||before.nlink!==1||before.size>MAX_FILE_BYTES)throw new ExportError('export-input','资料必须是单一普通文件且不超过2MiB');const handle=await open(file,constants.O_RDONLY|(constants.O_NOFOLLOW||0));try{const info=await handle.stat();if(info.dev!==before.dev||info.ino!==before.ino||!info.isFile()||info.nlink!==1||await checkedPath(root,relative)!==file)throw new ExportError('export-changed','资料采集期间身份变化，请重试');const bytes=await handle.readFile();cancel(options.signal);const identity=[info.dev,info.ino,info.size,info.mtimeMs,info.ctimeMs].join(':');const prior=captured.get(relative);if(prior&&(prior.digest!==hash(bytes)||prior.identity!==identity))throw new ExportError('export-changed','资料采集期间变化，请重试');if(!prior)inputBytes+=bytes.length;if(inputBytes>limits.inputBytes)throw new ExportError('export-limit','所选资料累计输入超过上限');captured.set(relative,{digest:hash(bytes),identity});return bytes.toString('utf8')}finally{await handle.close()}}
    const json=async(relative:string)=>{const value=await read(relative);if(value===null)throw new ExportError('export-missing','缺少登记文件：'+relative);try{return JSON.parse(value)}catch{throw new ExportError('export-invalid','登记JSON非法：'+relative)}}
    const project=await json('docs/specdev/project.json');if(project.schema!=='specdev/project/1'||typeof project.name!=='string'||!project.name.trim())throw new ExportError('export-invalid','项目登记不完整');const base='docs/specdev/'+context.businessId,business=await json(base+'/business.json');if(business.schema!=='specdev/business/1'||business.id!==context.businessId||typeof business.name!=='string'||!business.name.trim()||!Array.isArray(business.docs)||!business.docs.every((x:any)=>typeof x==='string'))throw new ExportError('export-invalid','业务登记/归属不完整');business.docs=[...new Set(business.docs)];for(const doc of business.docs)validPath(doc,false)
    const directory=await checkedPath(root,base);if(!directory)throw new ExportError('export-missing','业务目录缺失');const names=(await readdir(directory,{withFileTypes:true})).filter(x=>x.isDirectory()).map(x=>x.name).sort();const allCharts:string[]=[];for(const name of names){if(!idPattern.test(name))continue;const descriptor=await checkedPath(root,base+'/'+name+'/chart.json');if(descriptor)allCharts.push(name)}
    const available=[...business.docs.map((x:string)=>'doc:'+x),...allCharts.map(x=>'chart:'+x)],selected=options.materials===undefined?available:[...options.materials];if(new Set(selected).size!==selected.length||selected.some(x=>typeof x!=='string'||!available.includes(x)))throw new ExportError('export-forbidden','资料选择不属于当前业务或存在重复');if(selected.filter(x=>x.startsWith('doc:')).length>limits.documents||selected.filter(x=>x.startsWith('chart:')).length>limits.charts)throw new ExportError('export-limit','文档或图数量超过导出上限')
    const chartSets=new Map<string,any>();const chartDirectory:any[]=[]
    for(const chart of allCharts){
      if(!selected.includes('chart:'+chart)){chartDirectory.push({id:chart,name:chart,hasWorkflow:true});continue}
      try{const relative=base+'/'+chart,set=await readChartSet(name=>read(relative+'/'+name),chart);cancel(options.signal);if(inputBytes>limits.inputBytes)throw new ExportError('export-limit','资料累计输入超过上限');
        if(set.sourceError||Object.values(set.errors).length||set.contract.names.some(name=>set.files[TYPED_FILE_KEY[name]]==null))throw new ExportError('export-chart',set.sourceError||'所选图文件组缺失或读不开');
        if(chartRenderer(set.files.evidence)!=='3.0.1')throw new ExportError('export-unsupported','旧渲染器不支持离线导出，请取消选择');
        const descriptor=JSON.parse((await read(relative+'/chart.json'))!);parseChartContract(JSON.stringify(descriptor),chart);chartSets.set(chart,{...set,descriptor});chartDirectory.push({id:chart,name:descriptor.name,hasWorkflow:true,diagramType:set.contract.diagramType})
      }catch(error){const failed=error as ExportError;if(['export-cancelled','export-limit','export-changed'].includes(failed.code))throw failed;issues.push({code:failed.code||'export-chart',message:failed.message,materialId:'chart:'+chart});chartDirectory.push({id:chart,name:chart,hasWorkflow:true})}
    }
    const catalogBusiness={id:business.id,name:business.name,...(typeof business.intro==='string'?{intro:business.intro}:{}),docs:business.docs,charts:chartDirectory};const room=await readRoomLayout(root,context.businessId,{business:catalogBusiness,read:(_root,relative)=>read(relative)})
    const resources=JSON.parse(loaded.result['resources.json']);const catalogModule=await import(pathToFileURL(path.join(loaded.root,'web/assets/furniture/catalog.js')).href),placement=await import(pathToFileURL(path.join(loaded.root,'web/assets/rooms/placement.js')).href),binding=await import(pathToFileURL(path.join(loaded.root,'web/assets/rooms/bindings.js')).href);const library=await catalogModule.loadFurnitureCatalog({fetchJson:async(url:string)=>resources[url]});if(!library.ok)throw new ExportError('export-assets','正式家具目录无效');const catalog={schemaVersion:1,assets:[...resources['/specdev-workbench/assets/rooms/placeholder-catalog.json'].assets,...library.catalog.assets]},template=resources['/specdev-workbench/assets/rooms/templates.json'].templates.find((x:any)=>x.templateId===room.layout.templateRef);if(!template||!['ceramic','fairy'].includes(template.styleId))throw new ExportError('export-unsupported','房型不受当前导出支持');const validation=placement.validatePlacement(template,catalog,room.layout);if(!validation.ok)throw new ExportError('export-placement',validation.diagnostics.map((x:any)=>x.message).join('；'));const resolved=binding.resolveRoomBindings({business:room.business,layout:room.layout,catalog});if(!resolved.ok)throw new ExportError('export-bindings',resolved.diagnostics.map((x:any)=>x.message).join('；'))
    const documents:{path:string;text:string}[]=[],materials:ExportMaterial[]=[],charts:Record<string,{data:any}>={}
    for(const doc of business.docs){if(!selected.includes('doc:'+doc))continue;try{const text=await read(doc);if(text===null)throw new ExportError('export-missing','所选文档不存在');documents.push({path:doc,text});materials.push({id:'doc:'+doc,kind:'document',title:doc,sha256:hash(text)})}catch(error){issues.push({code:(error as ExportError).code||'export-document',message:(error as Error).message,materialId:'doc:'+doc})}}
    if(issues.length)return{ok:false,issues}
    const tempRoot=await realpath(context.temporaryRoot??tmpdir());if(inside(root,tempRoot))throw new ExportError('export-input','导出临时目录必须在业务仓之外');temporary=await mkdtemp(path.join(tempRoot,'specdev-room-export-'));const invoke=hooks.renderer??renderArchify;const renderer:typeof renderArchify=async(input,settings)=>{const result=await invoke(input,settings);if(!result.ok&&['render-stop-unconfirmed','render-native-abnormal'].includes(result.code)){cleanupSafe=false;rendererStopped=true}return result};intermediateBytes=inputBytes
    for(const [chart,set]of chartSets){try{cancel(options.signal);const type=set.contract.diagramType,graph=JSON.parse(set.files[set.contract.sourceKey]);if(graph?.diagram_type!==type)throw new ExportError('export-chart','图源与显式图种不符','chart:'+chart);const entities=graph[type==='lifecycle'?'states':'nodes'];if(!Array.isArray(entities))throw new ExportError('export-chart','图实体缺失','chart:'+chart);const missing=entities.filter((x:any)=>x.sources?.length).map((x:any)=>x.id);for(const entity of entities)for(const source of entity.sources??[])sourcePath(source)
      let projected=structuredClone(graph),references:any[]=[],status:ExportMaterial['sourceStatus']='none';const repo=graph.meta?.repository
      if(repo&&(!repo.url||!repo.revision))throw new ExportError('export-source','远端仓库身份或固定提交缺失','chart:'+chart)
      if(!repo){status=missing.length?'missing-remote':'none';for(const node of projected[type==='lifecycle'?'states':'nodes'])delete node.sources}
      let rendered=await renderer({repoRoot:root,graphId:context.businessId+'/'+chart,candidateText:JSON.stringify(projected),version:'3.0.1'},{tempRoot:temporary});if(!rendered.ok&&['render-stop-unconfirmed','render-native-abnormal'].includes(rendered.code))cleanupSafe=false;cancel(options.signal);if(!rendered.ok)throw new ExportError(rendered.code,rendered.error,'chart:'+chart)
      if(repo){const locationModule=await import(pathToFileURL(path.join(loaded.root,'vendor/archify-3.0.1/archify/renderers/shared/repository-location.mjs')).href);const location=locationModule.parseRepositoryRemote(repo.url,{authored:true});if(!location||!/^[a-f0-9]{40}$/i.test(repo.revision))throw new ExportError('export-source','来源仓库或完整提交非法','chart:'+chart);if((repo.link_mode??'web')==='web'){if(!['github','gitee'].includes(location.provider)||location.protocol!=='https:'||location.endpoint!=='standard')throw new ExportError('export-source','源码链接只支持规范HTTPS托管站','chart:'+chart);references=exportReferences(graph,type,context.businessId+'/'+chart,rendered.references);status='contract-verified'}else{status='missing-remote';for(const node of projected[type==='lifecycle'?'states':'nodes'])delete node.sources;delete projected.meta.repository;rendered=await renderer({repoRoot:root,graphId:context.businessId+'/'+chart,candidateText:JSON.stringify(projected),version:'3.0.1'},{tempRoot:temporary});cancel(options.signal);if(!rendered.ok)throw new ExportError(rendered.code,rendered.error,'chart:'+chart)}}
      intermediateBytes+=Buffer.byteLength(rendered.html)+Buffer.byteLength(JSON.stringify(set.files));if(intermediateBytes>limits.intermediateBytes)throw new ExportError('export-limit','图与冻结资料中间结果超过上限','chart:'+chart)
      delete projected.meta.output;const files={...set.files,...(type==='lifecycle'?{descriptor:JSON.stringify({schema:set.descriptor.schema,id:chart,name:set.descriptor.name,diagramType:type})}:{}),[set.contract.sourceKey]:JSON.stringify(projected),details:set.files.details.replace(/^.*（源码引用 [^\n]+）.*\n?/gm,''),evidence:JSON.stringify({schema:'specdev/evidence/1',renderer:'3.0.1',refs:[]})};charts[chart]={data:{title:set.descriptor.name,version:{diagramType:type,files},html:rendered.html,references,missingRemoteEntities:status==='missing-remote'?missing:[],contextId:'export-'+hash(JSON.stringify([context.businessId,chart,files]))}};materials.push({id:'chart:'+chart,kind:type,title:set.descriptor.name,sha256:hash(JSON.stringify(set.files)),sourceStatus:status,remoteReachability:'not-checked'})
      }catch(error){const failure=error as ExportError;if(['export-cancelled','export-limit'].includes(failure.code))throw failure;throw new ExportError(failure.code||'export-chart',failure.message,failure.materialId||'chart:'+chart)}
    }
    if(hooks.afterCapture)await hooks.afterCapture();cancel(options.signal)
    for(const [relative,entry]of captured){const text=await read(relative);if(entry.digest!=='missing'&&text===null)throw new ExportError('export-changed','资料组采集期间删除，请重试')}
    if(JSON.stringify((await readdir(directory,{withFileTypes:true})).filter(x=>x.isDirectory()).map(x=>x.name).sort())!==JSON.stringify(names))throw new ExportError('export-changed','业务目录采集期间变化，请重试')
    const browserRoom=structuredClone(room),missingByInstance:string[]=[];browserRoom.layout.instances=(browserRoom.layout.instances as any[]).map(({instanceId,assetId,placement})=>({instanceId,assetId,placement}));for(const entry of (browserRoom.layout.bindings??[]) as any[]){const omitted=(entry.documents??[]).some((x:string)=>!selected.includes('doc:'+x))||(entry.charts??[]).some((x:string)=>!selected.includes('chart:'+x));entry.documents=entry.documents.filter((x:string)=>selected.includes('doc:'+x));entry.charts=(entry.charts??[]).filter((x:string)=>selected.includes('chart:'+x));if(omitted&&!entry.documents.length&&!entry.charts.length)missingByInstance.push(entry.instanceId)}browserRoom.business.docs=documents.map(x=>x.path);browserRoom.business.charts=browserRoom.business.charts.filter(x=>selected.includes('chart:'+x.id))
    const payload=freeze({room:browserRoom,resources,documents,charts,missingByInstance,theme:options.theme,brightness:options.brightness,limits}),summary=freeze({format:ROOM_EXPORT_FORMAT,businessId:context.businessId,name:business.name,theme:options.theme,brightness:options.brightness,materials,sha256:hash(JSON.stringify([payload,loaded.manifestHash])),resourceSha256:loaded.manifestHash,preparedAt:new Date().toISOString(),limits}),prepared=Object.freeze({format:ROOM_EXPORT_FORMAT,summary});preparedData.set(prepared,{data:payload,assets:freeze(loaded.result)});return{ok:true,prepared,summary}
  }catch(error){const failure=error as ExportError;return{ok:false,issues:[{code:failure.code||'export-failed',message:failure.message.split(context.repoRoot).join('[业务仓]'),...(failure.materialId?{materialId:failure.materialId}:{})}]}}finally{try{if(temporary&&cleanupSafe){const info=await lstat(temporary);if(!info.isSymbolicLink()&&info.isDirectory()&&await realpath(temporary)===temporary&&path.basename(temporary).startsWith('specdev-room-export-'))await rm(temporary,{recursive:true,force:true})}}finally{operationInFlight=false}}
}
function safeJSON(value:any,limit:number){const raw=JSON.stringify(value),extra=(raw.match(/[<>&]/g)||[]).length*5+(raw.match(/[\u2028\u2029]/g)||[]).length*3;if(Buffer.byteLength(raw)+extra>limit)throw new ExportError('export-limit','分享HTML序列化超过输出上限');return raw.replaceAll('<','\\u003c').replaceAll('>','\\u003e').replaceAll('&','\\u0026').replaceAll('\u2028','\\u2028').replaceAll('\u2029','\\u2029')}
export async function generateRoomExport(prepared:PreparedRoomExport,{signal}:{signal?:AbortSignal}={}):Promise<GenerateResult>{if(operationInFlight)return{ok:false,issues:[{code:'export-busy',message:'已有导出任务在处理；本接口不无限排队'}]};if(rendererStopped)return{ok:false,issues:[{code:'export-renderer-stopped',message:'渲染停止状态待核实，本进程不自动重试'}]};operationInFlight=true;try{cancel(signal);const record=preparedData.get(prepared);if(!record)throw new ExportError('export-forbidden','只能装配本模块准备并冻结的结果');const data=record.data;await tick();cancel(signal);const loaded={result:record.assets},payload:any=structuredClone(data);payload.licenses=JSON.parse(loaded.result['licenses.json']);let bytes=0
  for(const chart of Object.values(payload.charts) as any[]){cancel(signal);chart.data.bridge=loaded.result['bridge.js'];const encoded=safeJSON(chart.data,data.limits.outputBytes),page=loaded.result['chart.html'].replace('<!-- ROOM_EXPORT_CHART_DATA -->',`<script type="application/json" id="room-export-chart-data">${encoded}</script>`).replace('<!-- ROOM_EXPORT_CHART_RUNTIME -->',`<script>${loaded.result['chart.js'].replace(/<\/script/gi,'<\\/script')}</script>`);bytes+=Buffer.byteLength(page);if(bytes>data.limits.intermediateBytes)throw new ExportError('export-limit','离线阅读页累计超过上限');delete chart.data;chart.page=page;await tick();cancel(signal)}
  payload.format=ROOM_EXPORT_FORMAT;const encoded=safeJSON(payload,data.limits.outputBytes),text=loaded.result['room.html'].replace('data-theme="dark"',`data-theme="${data.theme}"`).replace('<!-- ROOM_EXPORT_DATA -->',`<script id="room-export-data" type="application/json">${encoded}</script>`).replace('<!-- ROOM_EXPORT_RUNTIME -->',`<script>${loaded.result['room.js'].replace(/<\/script/gi,'<\\/script')}</script>`);cancel(signal);if(Buffer.byteLength(text)>data.limits.outputBytes)throw new ExportError('export-limit','分享HTML超过输出上限');const html=Buffer.from(text),name=Array.from(prepared.summary.name.normalize('NFC').replace(/[<>:"/\\|?*\u0000-\u001f]/g,'_')).slice(0,80).join('').replace(/[. ]+$/,'')||prepared.summary.businessId;return{ok:true,html,bytes:html.length,filename:name+' - 房间分享.html',sha256:hash(html),summary:prepared.summary}
}catch(error){const failure=error as ExportError;return{ok:false,issues:[{code:failure.code||'export-failed',message:failure.message}]}}finally{operationInFlight=false}}
